// Polyfill for crypto in case it's not global (though Node 20 should have it)
global.crypto = require('crypto');

const http = require('http');
const fs = require('fs');
const path = require('path');
const { connectToWhatsApp, sendMessage, getStatus, logout } = require('./socket');
const { WEBHOOK_SECRET, AUTH_DIR } = require('./config');

const PORT = 3000;

console.log('🚀 Starting WhatsApp Finance Bot (Baileys)...');

// 1. Start HTTP API Server
const server = http.createServer(async (req, res) => {
    // Enable CORS just in case
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Webhook-Secret');

    if (req.method === 'OPTIONS') {
        res.writeHead(200);
        res.end();
        return;
    }

    // Health Check
    if (req.url === '/health' && req.method === 'GET') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ status: 'ok' }));
        return;
    }

    // Send Message Endpoint
    if (req.url === '/send-message' && req.method === 'POST') {
        // Verify Secret
        const secret = req.headers['x-webhook-secret'];
        if (WEBHOOK_SECRET && secret !== WEBHOOK_SECRET) {
            res.writeHead(403, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: 'Unauthorized' }));
            return;
        }

        let body = '';
        req.on('data', chunk => {
            body += chunk.toString();
        });

        req.on('end', async () => {
            try {
                const data = JSON.parse(body);
                const { group_id, message } = data;

                if (!group_id || !message) {
                    res.writeHead(400, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ error: 'Missing group_id or message' }));
                    return;
                }

                console.log(`📤 Sending API message to ${group_id}`);
                await sendMessage(group_id, { text: message });

                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ success: true }));
            } catch (err) {
                console.error('API Send Error:', err);
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ error: err.message }));
            }
        });
        return;
    }

    // Status Endpoint
    if (req.url === '/status' && req.method === 'GET') {
        const status = getStatus();
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(status));
        return;
    }

    // Live QR page for WhatsApp linking. The QR rotates frequently, so this page
    // auto-refreshes and serves the newest /app/auth_info/qr.png generated by socket.js.
    if (req.url === '/qr' && req.method === 'GET') {
        const status = getStatus();
        res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
        res.end(`<!doctype html>
<html><head><meta charset="utf-8"><meta http-equiv="refresh" content="8"><title>Finance WhatsApp QR</title>
<style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#111;color:#eee}.card{background:#1d1d1d;padding:24px;border-radius:16px;text-align:center;box-shadow:0 8px 30px #0008}img{background:#fff;padding:12px;border-radius:12px;max-width:80vw}.ok{color:#4ade80}.warn{color:#facc15}</style></head>
<body><div class="card"><h1>Finance WhatsApp Bot</h1><p>Status: <b class="${status.status === 'connected' ? 'ok' : 'warn'}">${status.status}</b></p>${status.status === 'connected' ? '<p>✅ Connected. No QR needed.</p>' : '<img src="/qr.png?t=' + Date.now() + '" alt="WhatsApp QR"><p>Open WhatsApp → Linked devices → Link a device.<br>Page auto-refresh tiap 8 detik.</p>'}</div></body></html>`);
        return;
    }

    if (req.url?.startsWith('/qr.png') && req.method === 'GET') {
        const qrPath = path.join(AUTH_DIR, 'qr.png');
        fs.readFile(qrPath, (err, data) => {
            if (err) {
                res.writeHead(404, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
                res.end(JSON.stringify({ error: 'QR not available yet' }));
                return;
            }
            res.writeHead(200, { 'Content-Type': 'image/png', 'Cache-Control': 'no-store' });
            res.end(data);
        });
        return;
    }

    // Logout Endpoint
    if (req.url === '/logout' && req.method === 'POST') {
        const secret = req.headers['x-webhook-secret'];
        if (WEBHOOK_SECRET && secret !== WEBHOOK_SECRET) {
            res.writeHead(403, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: 'Unauthorized' }));
            return;
        }

        try {
            await logout();
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success: true, message: 'Logged out' }));
        } catch (err) {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: err.message }));
        }
        return;
    }

    // Debug: Group metadata
    if (req.url?.startsWith('/debug/group/') && req.method === 'GET') {
        const groupId = req.url.split('/debug/group/')[1];
        try {
            const sock = require('./socket');
            // Access the internal socket via a getter we'll add
            const meta = await sock.getGroupMetadata(groupId);
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify(meta, null, 2));
        } catch (err) {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: err.message }));
        }
        return;
    }

    // 404
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not Found' }));
});

// Start Server
server.listen(PORT, () => {
    console.log(`API Server running on port ${PORT}`);

    // Start WA logic after server is up
    connectToWhatsApp();
});

// Handle unhandled rejections
process.on('unhandledRejection', (err) => {
    console.error('Unhandled Rejection:', err);
});

process.on('uncaughtException', (err) => {
    console.error('Uncaught Exception:', err);
});
